name: Hava Durumu Botu

on:
  schedule:
    - cron: '58 5 * * *'
  workflow_dispatch:

jobs:
  botu-ayaga-kaldir:
    runs-on: ubuntu-latest

    steps:
      - name: Kodları GitHub'dan Çek
        uses: actions/checkout@v4

      - name: Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Kütüphaneleri Yükle.
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Botu Çalıştır.
        env: 
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          LATITUDE: ${{ secrets.LATITUDE }}
          LONGITUDE: ${{ secrets.LONGITUDE }}
        run: python main.py
